In [14]:
import pandas as pd
import os
from sqlalchemy import create_engine
import numpy as np
import db
from pygeodesy.ellipsoidalVincenty import LatLon
from pygeodesy.simplify import simplify1, simplifyRW, simplifyRDP
from pygeodesy.utily import wrap180
import plotly.express as px
connection_string = os.environ.get("DATABASE_URL", "postgresql://postgres:docker@127.0.0.1:5432")
engine = create_engine(connection_string)
from constants import decimated_url, full_url

In [15]:
df = pd.read_sql('SELECT * from cruises', engine)
df

,expocode,organization,investigators,platform_name,platform_type,qc_flag,socat_version
0,069920180814,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
1,069920180921,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
2,069920181126,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
3,069920190503,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
4,069920190509,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
...,...,...,...,...,...,...,...
9056,WFCH20250806,unassigned,Wanninkhof R. : Pierrot D.,Le Commandant Charcot,Ship,N,2026.0N
9057,WFCH20250905,unassigned,Wanninkhof R. : Pierrot D.,Le Commandant Charcot,Ship,N,2026.0N
9058,WFCH20251031,unassigned,Wanninkhof R. : Pierrot D.,Le Commandant Charcot,Ship,B,2026.0N
9059,WFCH20251112,unassigned,Wanninkhof R. : Pierrot D.,Le Commandant Charcot,Ship,B,2026.0N
9060,ZZ9920070416,Plymouth Marine Lab,"Kitidis, V.",WECO Timeseries,Ship,D,2.0N

In [16]:
final_length = 100
expos = list(df['expocode'].unique())
to_get =['expocode', 'time', 'latitude', 'longitude', 'platform_type']
vars = ','.join(to_get)
dtype_defs = {'expocode': 'str', 'time': 'str', 'latitude': np.float64, 'longitude': np.float64, 'platform_type': 'str'}
for idx, expo in enumerate(expos):
    turl = f'{decimated_url}.csv?{vars}&expocode="{expo}"'
    track = track = pd.read_csv(turl, skiprows=[1], dtype=dtype_defs)
    m = track.shape[0]
    if track.shape[0] > final_length:
        try:
            path_points = track[['latitude', 'longitude']].itertuples(index=False, name=None)
            latlon_points = [LatLon(lat, wrap180(lon)) for lat, lon in path_points]
            simplified_points = simplify1(latlon_points, distance=10_000, indices=True, wrap=True)
            track = track.iloc[simplified_points]
            track['expocode'] = track['expocode'].astype(str)
            # If you are doing this a second time, you might have to delete the cruise first
            # db.delete_track(expo)
            track.to_sql("tracks", con=engine, if_exists="append", index=False)
            print(f'{idx} {expo}:: initial size: {m}, final size: {track.shape[0]}')
        except Exception as e:
            print(e)
            print(f'{idx} {expo}:: initial size: {m}, unchanged')
    else:
        print(f'{idx} {expo}:: initial size: {m}, unchanged')

0 069920180814:: initial size: 35, unchanged
1 069920180921:: initial size: 8, unchanged
2 069920181126:: initial size: 8, unchanged
3 069920190503:: initial size: 17, unchanged
4 069920190509:: initial size: 167, final size: 111
5 069920190602:: initial size: 109, final size: 95
6 069920190803:: initial size: 91, unchanged
7 069920200703:: initial size: 151, final size: 124
8 069920201009:: initial size: 33, unchanged
9 069920201108:: initial size: 74, unchanged
10 069920201125:: initial size: 161, final size: 152
11 069920201211:: initial size: 126, final size: 112
12 069920201226:: initial size: 103, final size: 93
13 069920210106:: initial size: 164, final size: 147
14 069920211113:: initial size: 80, unchanged
15 069920220226:: initial size: 57, unchanged
16 069920230226:: initial size: 499, final size: 453
17 069920230424:: initial size: 163, final size: 142
18 069920230521:: initial size: 260, final size: 235
19 069920240501:: initial size: 194, final size: 150
20 06AQ19860627:: initial size: 129, final size: 121
21 06AQ19860928:: initial size: 185, final size: 148
22 06AQ19911114:: initial size: 86, unchanged
23 06AQ19911210:: initial size: 210, final size: 134
24 06AQ19921005:: initial size: 165, final size: 122
25 06AQ19930128:: initial size: 193, final size: 154
26 06AQ19930228:: initial size: 44, unchanged
27 06AQ19931019:: initial size: 247, final size: 217
28 06AQ19940524:: initial size: 125, final size: 109
29 06AQ19951112:: initial size: 116, final size: 107
30 06AQ19960320:: initial size: 149, final size: 126
31 06AQ19980411:: initial size: 144, final size: 111
32 06AQ19990327:: initial size: 102, final size: 68
33 06AQ20001004:: initial size: 233, final size: 195
34 06AQ20001026:: initial size: 277, final size: 171
35 06AQ20021126:: initial size: 104, final size: 68
36 06AQ20021214:: initial size: 456, final size: 207
37 06AQ20071203:: initial size: 500, final size: 219
38 06AQ20080209:: initial size: 424, final size: 261
39 06AQ20080416:: initial size: 227, final size: 121
40 06AQ20080624:: initial size: 201, final size: 76
41 06AQ20080705:: initial size: 1947, final size: 300
42 06AQ20090109:: initial size: 391, final size: 255
43 06AQ20090322:: initial size: 134, final size: 74
44 06AQ20090413:: initial size: 380, final size: 222
45 06AQ20090622:: initial size: 684, final size: 205
46 06AQ20090711:: initial size: 668, final size: 112
47 06AQ20090806:: initial size: 1364, final size: 503
48 06AQ20091023:: initial size: 267, final size: 120
49 06AQ20091129:: initial size: 478, final size: 321
50 06AQ20100131:: initial size: 1113, final size: 543
51 06AQ20100408:: initial size: 291, final size: 207
52 06AQ20101026:: initial size: 272, final size: 185
53 06AQ20110617:: initial size: 802, final size: 157
54 06AQ20110715:: initial size: 751, final size: 125
equirectangular4(89.9351, 84.8594, 89.9995, 9.4947, limit=45, wrap=True): delta (75.3647) exceeds limit (45)
55 06AQ20110806:: initial size: 1057, unchanged
56 06AQ20111214:: initial size: 366, final size: 150
57 06AQ20120108:: initial size: 551, final size: 335
58 06AQ20120318:: initial size: 413, final size: 149
59 06AQ20120411:: initial size: 343, final size: 258
60 06AQ20120615:: initial size: 1910, final size: 287
61 06AQ20120716:: initial size: 548, final size: 75
62 06AQ20120803:: initial size: 1010, final size: 418
63 06AQ20131110:: initial size: 304, final size: 184
64 06AQ20131220:: initial size: 1555, final size: 451
65 06AQ20131221:: initial size: 1555, final size: 451
66 06AQ20140309:: initial size: 391, final size: 260
67 06AQ20140608:: initial size: 837, final size: 225
68 06AQ20140707:: initial size: 449, final size: 151
equirectangular4(89.9372, 12.6618, 89.9515, 65.3564, limit=45, wrap=True): delta (52.6946) exceeds limit (45)
69 06AQ20140805:: initial size: 1121, unchanged
70 06AQ20141026:: initial size: 214, final size: 150
71 06AQ20141203:: initial size: 725, final size: 238
72 06AQ20150204:: initial size: 154, final size: 130
73 06AQ20150519:: initial size: 975, final size: 275
74 06AQ20150629:: initial size: 1152, final size: 245
equirectangular4(89.9606, 51.1297, 89.9994, 113.632, limit=45, wrap=True): delta (62.5021) exceeds limit (45)
75 06AQ20150818:: initial size: 718, unchanged
76 06AQ20151030:: initial size: 158, final size: 141
77 06AQ20151207:: initial size: 1191, final size: 437
78 06AQ20160220:: initial size: 567, final size: 294
79 06AQ20160412:: initial size: 169, final size: 147
80 06AQ20160614:: initial size: 1145, final size: 255
81 06AQ20160720:: initial size: 1555, final size: 301
82 06AQ20170205:: initial size: 792, final size: 230
83 06AQ20170321:: initial size: 97, unchanged
84 06AQ20170524:: initial size: 862, final size: 235
85 06AQ20170723:: initial size: 1735, final size: 151
86 06AQ20170822:: initial size: 490, final size: 132
87 06AQ20170912:: initial size: 505, final size: 180
88 06AQ202000301:: initial size: 73, unchanged
89 06AQ20200101:: initial size: 49, unchanged
90 06AQ20200201:: initial size: 62, unchanged
91 06AQ20200301:: initial size: 73, unchanged
92 06AQ20200401:: initial size: 96, unchanged
93 06AQ20200501:: initial size: 123, final size: 14
94 06AQ20200601:: initial size: 80, unchanged
95 06AQ20200701:: initial size: 416, final size: 36
equirectangular4(89.953, -32.699, 90.0, 31.672, limit=45, wrap=True): delta (64.371) exceeds limit (45)
96 06AQ20200801:: initial size: 660, unchanged
97 06AQ20200901:: initial size: 187, final size: 76
98 06AQ20201001:: initial size: 56, unchanged
99 06AQ20241224:: initial size: 1017, final size: 475
100 06AQ20250313:: initial size: 92, unchanged
101 06AQ20250401:: initial size: 141, final size: 106
102 06AQ20250529:: initial size: 1162, final size: 221
103 06AQ20250702:: initial size: 367, final size: 203
104 06BE19961010:: initial size: 55, unchanged
105 06BE19970515:: initial size: 277, final size: 181
106 06BE19970612:: initial size: 1199, final size: 252
107 06BE20091009:: initial size: 39, unchanged
108 06BE20140710:: initial size: 34, unchanged
109 06BE20140723:: initial size: 39, unchanged
110 06CK20060523:: initial size: 100, unchanged
111 06CK20060715:: initial size: 153, final size: 142
112 06CK20060821:: initial size: 102, final size: 97
113 06GA19960613:: initial size: 381, final size: 206
114 06LB19831130:: initial size: 66, unchanged
115 06LB19840107:: initial size: 31, unchanged
116 06LB19840629:: initial size: 53, unchanged
117 06LB19850110:: initial size: 108, final size: 108
118 06LB19850313:: initial size: 82, unchanged
119 06LB19850812:: initial size: 114, final size: 114
120 06LB19860116:: initial size: 43, unchanged
121 06LB19860323:: initial size: 42, unchanged
122 06LB19860801:: initial size: 41, unchanged
123 06LB19861011:: initial size: 62, unchanged
124 06LB19861214:: initial size: 88, unchanged
125 06LB19870221:: initial size: 118, final size: 116
126 06LB19870501:: initial size: 309, final size: 305
127 06LB19870721:: initial size: 87, unchanged
128 06LB19870920:: initial size: 146, final size: 146
129 06LB19871126:: initial size: 269, final size: 268
130 06LB19871231:: initial size: 131, final size: 131
131 06LB19880204:: initial size: 90, unchanged
132 06M220060524:: initial size: 546, final size: 282
133 06M220110623:: initial size: 95, unchanged
134 06M220180302:: initial size: 128, final size: 102
135 06M220200117:: initial size: 84, unchanged
136 06M320120320:: initial size: 56, unchanged
137 06M320120407:: initial size: 146, final size: 90
138 06MQ20210509:: initial size: 719, final size: 279
139 06MQ20210627:: initial size: 219, final size: 102
140 06MT19910903:: initial size: 104, final size: 87
141 06MT19920510:: initial size: 101, final size: 82
142 06MT19921229:: initial size: 110, final size: 94
143 06MT19941012:: initial size: 168, final size: 112
144 06MT19941119:: initial size: 118, final size: 79
145 06MT19950714:: initial size: 448, final size: 167
146 06MT19960607:: initial size: 167, final size: 117
147 06MT19960622:: initial size: 385, final size: 127
148 06MT19970106:: initial size: 30, unchanged
149 06MT19970516:: initial size: 411, final size: 266
150 06MT19970707:: initial size: 1089, final size: 363
151 06MT19970814:: initial size: 221, final size: 133
152 06MT19981228:: initial size: 44, unchanged
153 06MT20021015:: initial size: 153, final size: 131
154 06MT20060714:: initial size: 288, final size: 132
155 06P119910616:: initial size: 31, unchanged
156 06P119950901:: initial size: 133, final size: 98
157 06PO20050322:: initial size: 557, final size: 114
158 06PO20070210:: initial size: 110, final size: 62
159 096U20170515:: initial size: 143, final size: 95
160 06PO20100531:: initial size: 371, final size: 107
161 06ZG20091213:: initial size: 81, unchanged
162 06ZG20100115:: initial size: 121, final size: 108
163 06ZG20100207:: initial size: 84, unchanged
164 06ZG20100226:: initial size: 90, unchanged
165 06ZG20100321:: initial size: 80, unchanged
166 06ZG20100409:: initial size: 70, unchanged
167 06ZG20100506:: initial size: 94, unchanged
168 06ZG20100716:: initial size: 66, unchanged
169 06ZG20100813:: initial size: 113, final size: 109
170 06ZG20100902:: initial size: 78, unchanged
171 06ZG20100930:: initial size: 92, unchanged
172 06ZG20101023:: initial size: 78, unchanged
173 06ZG20101118:: initial size: 51, unchanged
174 06ZG20101211:: initial size: 33, unchanged
175 07AL19951011:: initial size: 245, final size: 54
176 07AL19960218:: initial size: 141, final size: 61
177 07AL19970201:: initial size: 170, final size: 77
178 07AL19970503:: initial size: 660, final size: 199
179 07AL19971101:: initial size: 1181, final size: 787
180 07AL19980701:: initial size: 122, final size: 44
181 07AL19990718:: initial size: 75, unchanged
182 07AL19991101:: initial size: 450, final size: 193
183 07AL19991129:: initial size: 312, final size: 141
184 07AL20000113:: initial size: 230, final size: 125
185 07AL20000210:: initial size: 147, final size: 88
186 07AL20000305:: initial size: 255, final size: 154
187 07AL20010513:: initial size: 257, final size: 92
188 07AL20010607:: initial size: 88, unchanged
189 07AL20010709:: initial size: 180, final size: 100
190 07AL20010802:: initial size: 73, unchanged
191 08AI20000324:: initial size: 162, final size: 137
192 08AI20010124:: initial size: 217, final size: 181
193 08AI20010808:: initial size: 82, unchanged
194 08AI20020131:: initial size: 259, final size: 227
195 08AI20030206:: initial size: 120, final size: 109
196 08AI20040227:: initial size: 272, final size: 217
197 08AI20041225:: initial size: 158, final size: 125
198 08D820170918:: initial size: 173, final size: 102
199 08D820180810:: initial size: 10, unchanged
200 08D820180818:: initial size: 330, final size: 85
201 08D820190124:: initial size: 45, unchanged
202 08D820191014:: initial size: 71, unchanged
203 08D820191117:: initial size: 191, final size: 103
204 08D820191205:: initial size: 158, final size: 73
205 08D820221204:: initial size: 280, final size: 113
206 08D820230227:: initial size: 581, final size: 332
207 08D820230415:: initial size: 160, final size: 73
208 08D820230521:: initial size: 209, final size: 124
209 08D820240120:: initial size: 529, final size: 271
210 08D820240318:: initial size: 123, final size: 62
211 08D820240501:: initial size: 365, final size: 124
212 08D820240701:: initial size: 353, final size: 185
213 08D820240815:: initial size: 575, final size: 269
214 08D820241020:: initial size: 668, final size: 251
215 08D820241130:: initial size: 177, final size: 87
216 08D820250128:: initial size: 387, final size: 245
217 08D820250401:: initial size: 337, final size: 205
218 08D820250514:: initial size: 222, final size: 125
219 08D820250701:: initial size: 408, final size: 211
220 08D820250808:: initial size: 739, final size: 379
221 08D820251022:: initial size: 678, final size: 325
222 08PD20051019:: initial size: 178, final size: 130
223 08PD20060310:: initial size: 362, final size: 298
224 08PD20060907:: initial size: 268, final size: 202
225 096U20150321:: initial size: 17, unchanged
226 096U20160108:: initial size: 628, final size: 349
227 096U20160314:: initial size: 216, final size: 156
228 096U20160426:: initial size: 162, final size: 141
229 096U20160630:: initial size: 64, unchanged
230 096U20160817:: initial size: 38, unchanged
231 096U20160825:: initial size: 78, unchanged
232 096U20160831:: initial size: 299, final size: 168
233 096U20160927:: initial size: 79, unchanged
234 096U20161028:: initial size: 31, unchanged
235 096U20170114:: initial size: 491, final size: 321
236 096U20170319:: initial size: 53, unchanged
237 096U20170411:: initial size: 115, final size: 89
238 096U20170504:: initial size: 161, final size: 65
239 096U20170831:: initial size: 99, unchanged
240 096U20170924:: initial size: 183, final size: 120
241 096U20171011:: initial size: 191, final size: 106
242 096U20171125:: initial size: 136, final size: 102
243 096U20180111:: initial size: 308, final size: 220
244 096U20180302:: initial size: 106, final size: 61
245 096U20180405:: initial size: 53, unchanged
246 096U20180418:: initial size: 72, unchanged
247 096U20180514:: initial size: 82, unchanged
248 096U20180528:: initial size: 129, final size: 63
249 096U20180820:: initial size: 29, unchanged
250 096U20180911:: initial size: 204, final size: 133
251 096U20181017:: initial size: 170, final size: 124
252 096U20181122:: initial size: 207, final size: 79
253 096U20181227:: initial size: 124, final size: 101
254 096U20190118:: initial size: 588, final size: 312
255 096U20190314:: initial size: 79, unchanged
256 096U20190514:: initial size: 96, unchanged
257 096U20190730:: initial size: 7, unchanged
258 096U20190807:: initial size: 56, unchanged
259 096U20190909:: initial size: 72, unchanged
260 096U20191003:: initial size: 127, final size: 62
261 096U20191019:: initial size: 543, final size: 196
262 096U20191223:: initial size: 172, final size: 124
263 096U20200110:: initial size: 329, final size: 265
264 096U20200730:: initial size: 124, final size: 20
265 096U20200827:: initial size: 53, unchanged
266 096U20201008:: initial size: 272, final size: 188
267 096U20201113:: initial size: 158, final size: 73
268 096U20201204:: initial size: 135, final size: 86
269 096U20210129:: initial size: 622, final size: 434
270 096U20210414:: initial size: 93, unchanged
271 096U20210508:: initial size: 169, final size: 127
272 096U20210611:: initial size: 87, unchanged
273 096U20210630:: initial size: 141, final size: 128
274 096U20211110:: initial size: 144, final size: 29
275 096U20211119:: initial size: 128, final size: 78
276 096U20211130:: initial size: 96, unchanged
277 096U20211214:: initial size: 41, unchanged
278 096U20220319:: initial size: 225, final size: 157
279 096U20220504:: initial size: 110, final size: 78
280 096U20220528:: initial size: 329, final size: 201
281 096U20220714:: initial size: 44, unchanged
282 096U20220815:: initial size: 42, unchanged
283 096U20220910:: initial size: 67, unchanged
284 096U20220930:: initial size: 113, final size: 88
285 096U20230125:: initial size: 314, final size: 240
286 096U20230323:: initial size: 374, final size: 206
287 096U20230511:: initial size: 79, unchanged
288 096U20230605:: initial size: 33, unchanged
289 096U20230629:: initial size: 249, final size: 125
290 096U20230913:: initial size: 225, final size: 95
291 096U20231009:: initial size: 191, final size: 123
292 096U20231103:: initial size: 64, unchanged
293 096U20231115:: initial size: 215, final size: 157
294 096U20240105:: initial size: 541, final size: 299
295 096U20240309:: initial size: 115, final size: 81
296 096U20240330:: initial size: 121, final size: 88
297 096U20240430:: initial size: 331, final size: 97
298 096U20240607:: initial size: 94, unchanged
299 096U20250307:: initial size: 88, unchanged
300 096U20250325:: initial size: 109, final size: 76
301 096U20250428:: initial size: 151, final size: 84
302 096U20250526:: initial size: 283, final size: 110
303 096U20250701:: initial size: 49, unchanged
304 096U20250726:: initial size: 38, unchanged
305 099920220221:: initial size: 786, final size: 478
306 09AR19910926:: initial size: 97, unchanged
307 09AR19921019:: initial size: 149, final size: 130
308 09AR19930105:: initial size: 804, final size: 524
309 09AR19930311:: initial size: 152, final size: 126
310 09AR19930807:: initial size: 308, final size: 263
311 09AR19931119:: initial size: 352, final size: 249
312 09AR19940101:: initial size: 593, final size: 423
313 09AR19940831:: initial size: 18, unchanged
314 09AR19941213:: initial size: 243, final size: 184
315 09AR19950717:: initial size: 32, unchanged
316 09AR19950916:: initial size: 34, unchanged
317 09AR19951116:: initial size: 51, unchanged
318 09AR19960119:: initial size: 562, final size: 403
319 09AR19960822:: initial size: 56, unchanged
320 09AR19970910:: initial size: 22, unchanged
321 09AR19971114:: initial size: 54, unchanged
322 09AR19980228:: initial size: 70, unchanged
323 09AR19980404:: initial size: 7, unchanged
324 09AR19980715:: initial size: 42, unchanged
325 09AR19990205:: initial size: 40, unchanged
326 09AR19990716:: initial size: 68, unchanged
327 09AR20011031:: initial size: 225, final size: 130
328 09AR20060102:: initial size: 974, final size: 572
329 09AR20110104:: initial size: 488, final size: 217
330 09AR20110222:: initial size: 553, final size: 221
331 09AR20120105:: initial size: 346, final size: 201
332 09AR20120215:: initial size: 298, final size: 218
333 09AR20120317:: initial size: 1255, final size: 300
334 09AR20120416:: initial size: 104, final size: 73
335 09AR20120914:: initial size: 136, final size: 101
336 09AR20121116:: initial size: 675, final size: 257
337 09AR20121217:: initial size: 822, final size: 181
338 09AR20130113:: initial size: 180, final size: 126
339 09AR20130228:: initial size: 162, final size: 73
340 09AR20131015:: initial size: 302, final size: 159
equirectangular4(-56.4218, 126.244, -67.146, 73.7061, limit=45, wrap=True): delta (52.5375) exceeds limit (45)
341 09AR20140129:: initial size: 145, unchanged
342 09AR20140309:: initial size: 227, final size: 173
343 09AR20141022:: initial size: 135, final size: 109
344 09AR20141205:: initial size: 902, final size: 342
345 09AR20150128:: initial size: 625, final size: 368
346 09AR20151022:: initial size: 39, unchanged
347 09AR20151028:: initial size: 257, final size: 186
348 09AR20151201:: initial size: 102, final size: 42
349 09AR20151209:: initial size: 202, final size: 139
350 09AR20160111:: initial size: 622, final size: 343
351 09AR20161021:: initial size: 14, unchanged
352 09AR20161026:: initial size: 256, final size: 215
353 09AR20161208:: initial size: 1118, final size: 350
354 09AR20170125:: initial size: 505, final size: 324
355 09AR20170314:: initial size: 115, final size: 60
356 09AR20171029:: initial size: 247, final size: 158
357 09AR20171213:: initial size: 358, final size: 193
358 09AR20180115:: initial size: 1339, final size: 388
359 09AR20180308:: initial size: 112, final size: 74
360 09AR20181025:: initial size: 300, final size: 196
361 09AR20181206:: initial size: 837, final size: 144
362 09AR20190305:: initial size: 230, final size: 79
363 09AR20191025:: initial size: 278, final size: 199
364 09AR20191201:: initial size: 242, final size: 174
365 09AR20191222:: initial size: 636, final size: 117
366 09AR20200121:: initial size: 700, final size: 402
367 09AR20200310:: initial size: 119, final size: 80
368 09DB20180327:: initial size: 133, final size: 82
369 09DB20180328:: initial size: 224, final size: 124
370 09DB20190814:: initial size: 21, unchanged
371 09F920180926:: initial size: 232, final size: 2
372 09F920190419:: initial size: 101, final size: 2
373 09F920191002:: initial size: 68, unchanged
374 09F920191214:: initial size: 140, final size: 2
375 09F920200522:: initial size: 190, final size: 2
376 09F920201118:: initial size: 175, final size: 2
377 09F920210523:: initial size: 125, final size: 2

In [21]:
all = pd.read_sql("SELECT * FROM TRACKS WHERE platform_type != 'Mooring' LIMIT 10000", con=engine)
all = all.sort_values(['expocode', 'time'])
figure = px.line_geo(all, lat='latitude', lon='longitude', color='expocode', 
                        hover_data=['expocode', 'time', 'latitude', 'longitude'],
                    )
figure.show()

In [22]:
tdf = pd.read_sql("SELECT distinct expocode FROM tracks WHERE platform_type != 'Mooring' LIMIT 200", con=engine)
tdf

         expocode
0    74EQ20140320
1    MHAL20240618
2    WFCH20220424
3    33OA20250518
4    34FM20230612
..            ...
195  33GG20210816
196  11BE20030901
197  58US20190228
198  58G220230426
199  31FN20100612

[200 rows x 1 columns]

In [23]:
in_set = "','".join(list(tdf['expocode']))
in_set = "'" + in_set + "'"
in_set

"'74EQ20140320','MHAL20240618','WFCH20220424','33OA20250518','34FM20230612','64PE20011106','320G20110503','06AQ20090806','77XT20211018','49P120120502','49P120100527','11BE19990914','33RO20050712','ZZ9920070416','33LG20111102','642B20120526','45CE20190428','34FM20150101','33GG20130810','09F920211101','26T320240517','08AI20010124','35MJ20230526','34FM20100902','58G220250618','35MV20220420','65DK20150729','26NA20170803','74X120101214','33BI20250427','PAT520201001','33KF20101107','06AQ20110617','18SN20160925','34FP20060430','PAT520240715','320620130103','58GS20040825','26NA20060728','06MQ20210627','325020190520','26RA20220420','BHNQ20200420','91AA20221219','91AA20090202','46BS20070206','35MJ20140704','33HH20140411','09SS20080228','58G220210801','PANC20250925','33HH20170502','34FM20111110','49P120070228','34FM20110302','33H320170110','49WB20180626','18VJ20191003','61TG20240104','49P120070704','320620230118','49OX20220619','PWAR20090215','33LG20151118','33RO20140321','33HH20130610','PANC20150826','33LG20041108','09SS20100508','PANC20140411','35AQ20120425','PANC20141114','34FM20250601','46FR20250505','31FN20090904','77XT20210503','33RR20230722','77IH20170520','65DK20170423','09AR20181206','BHNQ20080701','33LG20170712','33BI20210626','61TG20180205','18PZ19880627','58SC19970526','PANC20171208','BHNQ20090807','49P120020827','49NZ20071009','26NA20140612','34FM20180423','09R920200306','33LG20211222','29HE20070321','33KF20060617','320620160907','PAT520250331','33KM20000615','33BI20220606','11SS20250101','49UP19960424','33LG20180413','319920101120-2','33GG20140821','320620060228','740H20200119','58GS20161005','11SS20250401','331I20200504','28AQ20191117','26RA20250417','33KF20070928','49P120050621','09AR20180308','33KF20110929','65DK20170225','77XT20210730','492C20000428','26NA20070427','AGFO20151226','34FM20220701','33H320100717','65DK20210130','34FM20110930','PAT520131119','34FM20080701','33GG20180902','74WX20220905','46FR20240504','26RA20210307','332220190921','58GS20170410','332220110820','096U20171125','32DB20170717','58NC20060717','58SC19950711','33RO20070710','PAT520220414','PANC20140427','49P120041112','33KF20120319','BHNQ20070521','32DB20110804','320620130513','58NC20060802','91AA20191217','33LG20141028','26RA20250425','49HH19900903','PAT520101026','33GG20150708','320620070401','33KM20040327','49HH19831123','49WA20200710','332220250311','33RO19980525','BHNQ20080526','WFCH20240926','33LG20060321','BMBE20130702','PANC20160928','740720160120','PANC20220820','49P120121225','33HH20180812','33LG20030923','33WA20250124','33GG20250903','34FP20040601','PAT520161130','33HQ20220712','26NA20090713','58G220230201','MLCE20160702','33HH20150812','WFCH20240528','49UP20150604','319920111109','MLSC20231201','91AH20150722','33LG20081231','49P120071218','33KF20110521','33GG20170809','45CE20250617','PANC20190515','11SS20211101','PANC20240821','49UF20200730','08D820230415','MHAL20250802','49UP20070607','33GG20210816','11BE20030901','58US20190228','58G220230426','31FN20100612'"

In [24]:
hdf = pd.read_sql(f"SELECT * FROM tracks WHERE expocode IN ({in_set})", con=engine)
hdf

           expocode                  time  latitude  longitude  platform_type
0      06MQ20210627  2021-06-27T15:35:00Z   51.0700     2.3100  sailing yacht
1      06MQ20210627  2021-06-27T16:45:00Z   51.0600     2.1600  sailing yacht
2      06MQ20210627  2021-06-27T18:13:00Z   51.0300     1.9400  sailing yacht
3      06MQ20210627  2021-06-27T19:13:00Z   51.0000     1.7500  sailing yacht
4      06MQ20210627  2021-06-27T20:59:00Z   50.8800     1.4200  sailing yacht
...             ...                   ...       ...        ...            ...
44251  06AQ20110617  2011-07-14T11:07:29Z   79.0745     4.1036           Ship
44252  06AQ20110617  2011-07-14T15:02:15Z   79.1057     5.0339           Ship
44253  06AQ20110617  2011-07-14T15:09:24Z   79.1086     5.1355           Ship
44254  06AQ20090806  2009-08-06T13:02:34Z   66.5041   -23.6968           Ship
44255  06AQ20090806  2009-08-06T13:48:39Z   66.6130   -23.4857           Ship

[44256 rows x 5 columns]

In [25]:
sdf = pd.read_sql("SELECT distinct expocode FROM tracks WHERE platform_type = 'Mooring' LIMIT 20", con=engine)
sdf

        expocode
0   09F920230518
1   09F920231105
2   09F920240413
3   09F920241125
4   09F920250409
5   09FS20091009
6   09FS20100421
7   09FS20100908
8   09FS20110311
9   09FS20110826
10  09FS20111018
11  09FS20120208
12  09FS20120417
13  09FS20160805
14  09FS20160912
15  09FS20161129
16  09FS20170207
17  09FS20170306
18  09FS20170520
19  09FS20170907

In [26]:
in_buoy = "','".join(list(sdf['expocode']))
in_buoy = "'" + in_buoy + "'"
in_buoy

"'09F920230518','09F920231105','09F920240413','09F920241125','09F920250409','09FS20091009','09FS20100421','09FS20100908','09FS20110311','09FS20110826','09FS20111018','09FS20120208','09FS20120417','09FS20160805','09FS20160912','09FS20161129','09FS20170207','09FS20170306','09FS20170520','09FS20170907'"

In [27]:
bdf = pd.read_sql(f"SELECT * FROM tracks WHERE expocode IN ({in_buoy})", con=engine)
bdf

        expocode                  time  latitude  longitude platform_type
0   09F920230518  2023-05-18T18:00:00Z  -42.6078   148.2253       Mooring
1   09F920230518  2023-11-04T20:00:00Z  -42.6078   148.2253       Mooring
2   09F920231105  2023-11-05T16:00:00Z  -42.6042   148.2310       Mooring
3   09F920231105  2024-04-13T00:00:00Z  -42.6042   148.2310       Mooring
4   09F920240413  2024-04-13T20:00:00Z  -42.5996   148.2331       Mooring
5   09F920240413  2024-11-24T20:00:00Z  -42.5996   148.2331       Mooring
6   09F920241125  2024-11-25T16:00:00Z  -42.6037   148.2329       Mooring
7   09F920241125  2025-04-08T22:00:00Z  -42.6037   148.2329       Mooring
8   09F920250409  2025-04-09T18:00:00Z  -42.6027   148.2359       Mooring
9   09F920250409  2025-10-28T20:00:00Z  -42.6027   148.2359       Mooring
10  09FS20091009  2009-10-09T06:00:00Z  -23.4586   151.9268       Mooring
11  09FS20091009  2010-04-19T21:00:00Z  -23.4586   151.9268       Mooring
12  09FS20100421  2010-04-22T03:00:00Z  -23.4585   151.9267       Mooring
13  09FS20100421  2010-09-06T00:00:00Z  -23.4585   151.9267       Mooring
14  09FS20100908  2010-09-08T08:00:00Z  -23.4609   151.9276       Mooring
15  09FS20100908  2011-03-08T22:00:00Z  -23.4609   151.9276       Mooring
16  09FS20110311  2011-03-11T06:00:00Z  -23.4223   151.6911       Mooring
17  09FS20110311  2011-08-19T22:00:00Z  -23.4223   151.6911       Mooring
18  09FS20110826  2011-08-26T06:00:00Z  -23.4618   151.9279       Mooring
19  09FS20110826  2012-03-23T22:00:00Z  -23.4618   151.9279       Mooring
20  09FS20111018  2011-10-18T04:00:00Z  -42.5979   148.2375       Mooring
21  09FS20111018  2012-04-15T22:00:00Z  -42.5979   148.2375       Mooring
22  09FS20120208  2012-02-08T03:00:00Z  -35.8379   136.4448       Mooring
23  09FS20120208  2012-11-26T21:00:00Z  -35.8379   136.4448       Mooring
24  09FS20120417  2012-04-17T06:00:00Z  -42.5962   148.2375       Mooring
25  09FS20120417  2012-10-18T20:00:00Z  -42.5962   148.2375       Mooring
26  09FS20160805  2016-08-05T08:00:00Z  -42.5942   148.2333       Mooring
27  09FS20160805  2017-02-06T22:00:00Z  -42.5942   148.2333       Mooring
28  09FS20160912  2016-09-12T06:00:00Z  -23.4578   151.9310       Mooring
29  09FS20160912  2017-02-20T00:00:00Z  -23.4578   151.9310       Mooring
30  09FS20161129  2016-11-29T04:00:00Z  -35.8392   136.4550       Mooring
31  09FS20161129  2017-05-18T20:00:00Z  -35.8392   136.4550       Mooring
32  09FS20170207  2017-02-07T10:00:00Z  -42.6023   148.2335       Mooring
33  09FS20170207  2017-09-11T22:00:00Z  -42.6023   148.2335       Mooring
34  09FS20170306  2017-03-06T06:00:00Z  -23.4587   151.9249       Mooring
35  09FS20170306  2017-09-04T22:00:00Z  -23.4587   151.9249       Mooring
36  09FS20170520  2017-05-20T14:00:00Z  -35.8352   136.4453       Mooring
37  09FS20170520  2017-12-05T20:00:00Z  -35.8352   136.4453       Mooring
38  09FS20170907  2017-09-07T12:00:00Z  -23.4582   151.9248       Mooring
39  09FS20170907  2018-02-11T22:00:00Z  -23.4582   151.9248       Mooring

In [28]:
import plotly.express as px
import plotly.graph_objects as go
# figure = go.Figure()
# if hdf.shape[0] > 100_000:
#     hdf = hdf.sample(n=100_000)
# expos = list(hdf['expocode'].unique())
# for ex in expos:
#     plot_df = hdf.loc[hdf['expocode']==ex]
#     plot_df = plot_df.sort_values(['time'])
#     trace = go.Scattergeo(lat=plot_df['latitude'], lon=plot_df['longitude'], mode='lines', name=ex)
#     figure.add_trace(trace)
# # figure = px.scatter_geo(hdf, lat='latitude', lon='longitude', color='expocode')
# figure
if hdf.shape[0] > 100_000:
    hdf = hdf.sample(n=100_000)
hdf = hdf.sort_values(['expocode', 'time'])
figure = px.line_geo(hdf, lat='latitude', lon='longitude', color='expocode')
buoy = px.scatter_geo(bdf, lat='latitude', lon='longitude', color='expocode')
figure.add_traces(list(buoy.select_traces()))
figure.show()