In [3]:
import pandas as pd
import os
from sqlalchemy import create_engine
import numpy as np
import db
from pygeodesy.ellipsoidalVincenty import LatLon
from pygeodesy.simplify import simplify1, simplifyRW, simplifyRDP
from pygeodesy.utily import wrap180
import plotly.express as px
connection_string = os.environ.get("DATABASE_URL", "postgresql://postgres:docker@127.0.0.1:5432")
engine = create_engine(connection_string)
decimated_url = 'https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated'
full_url = 'https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_fulldata'

In [4]:
df = pd.read_sql('SELECT * from cruises', engine)
df

,expocode,organization,investigators,platform_name,platform_type,qc_flag,socat_version
0,069920180814,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
1,069920180921,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
2,069920181126,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
3,069920190503,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
4,069920190509,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
...,...,...,...,...,...,...,...
8269,WFCH20240426,NOAA AOML,"Wanninkhof, R. : Pierrot, D.",Le Commandant Charcot,Ship,B,2025.0N
8270,WFCH20240506,NOAA AOML,"Wanninkhof, R. : Pierrot, D.",Le Commandant Charcot,Ship,B,2025.0N
8271,WFCH20240516,NOAA AOML,"Wanninkhof, R. : Pierrot, D.",Le Commandant Charcot,Ship,B,2025.0N
8272,WFCH20240528,NOAA AOML,"Wanninkhof, R. : Pierrot, D.",Le Commandant Charcot,Ship,B,2025.0N
8273,ZZ9920070416,Plymouth Marine Lab,"Kitidis, V.",WECO Timeseries,Ship,D,2.0N

In [6]:
final_length = 100
expos = list(df['expocode'].unique())
for idx, expo in enumerate(expos):
    if idx > 10:
        track = db.get_track(expo)
        m = track.shape[0]
        if track.shape[0] > final_length:
            try:
                path_points = track[['latitude', 'longitude']].itertuples(index=False, name=None)
                latlon_points = [LatLon(lat, wrap180(lon)) for lat, lon in path_points]
                simplified_points = simplify1(latlon_points, distance=10_000, indices=True, wrap=True)
                track = track.iloc[simplified_points]
                track['expocode'] = track['expocode'].astype(str)
                db.delete_track(expo)
                track.to_sql("tracks", con=engine, if_exists="append", index=False)
                print(f'{expo}:: initial size: {m}, final size: {track.shape[0]}')
            except Exception as e:
                print(e)
                print(f'{expo}:: initial size: {m}, unchanged')
        else:
            print(f'{expo}:: initial size: {m}, unchanged')

equirectangular4(-54.1874, -151.859, -54.5458, 162.855, limit=45, wrap=True): delta (45.286) exceeds limit (45)
069920201211:: initial size: 238, unchanged
069920201226:: initial size: 103, final size: 93
069920210106:: initial size: 164, final size: 147
069920211113:: initial size: 80, unchanged
069920220226:: initial size: 57, unchanged
069920230226:: initial size: 499, final size: 453
069920230424:: initial size: 163, final size: 142
069920230521:: initial size: 260, final size: 235

069920240501:: initial size: 194, final size: 150
06AQ19860627:: initial size: 129, final size: 121
06AQ19860928:: initial size: 185, final size: 148
06AQ19911114:: initial size: 86, unchanged
06AQ19911210:: initial size: 210, final size: 134
06AQ19921005:: initial size: 165, final size: 122
06AQ19930128:: initial size: 193, final size: 154
06AQ19930228:: initial size: 44, unchanged
06AQ19931019:: initial size: 247, final size: 217
06AQ19940524:: initial size: 125, final size: 109
06AQ19951112:: initial size: 116, final size: 107
06AQ19960320:: initial size: 149, final size: 126
06AQ19980411:: initial size: 144, final size: 111
06AQ19990327:: initial size: 102, final size: 68
06AQ20001004:: initial size: 233, final size: 195
06AQ20001026:: initial size: 277, final size: 171
06AQ20021126:: initial size: 104, final size: 68
06AQ20021214:: initial size: 456, final size: 207
06AQ20071203:: initial size: 500, final size: 219
06AQ20080209:: initial size: 424, final size: 261
06AQ20080416:: initial size: 227, final size: 121
06AQ20080624:: initial size: 201, final size: 76
06AQ20080705:: initial size: 1947, final size: 300
06AQ20090109:: initial size: 391, final size: 255
06AQ20090322:: initial size: 134, final size: 74
06AQ20090413:: initial size: 380, final size: 222
06AQ20090622:: initial size: 684, final size: 205
06AQ20090711:: initial size: 668, final size: 112
06AQ20090806:: initial size: 1364, final size: 503
06AQ20091023:: initial size: 267, final size: 120
06AQ20091129:: initial size: 478, final size: 321
06AQ20100131:: initial size: 1113, final size: 543
06AQ20100408:: initial size: 291, final size: 207
06AQ20101026:: initial size: 272, final size: 185
06AQ20110617:: initial size: 802, final size: 157
06AQ20110715:: initial size: 751, final size: 125
equirectangular4(89.9351, 84.8594, 89.9995, 9.4947, limit=45, wrap=True): delta (75.3647) exceeds limit (45)
06AQ20110806:: initial size: 1057, unchanged
06AQ20111214:: initial size: 366, final size: 150
06AQ20120108:: initial size: 551, final size: 335
06AQ20120318:: initial size: 413, final size: 149
06AQ20120411:: initial size: 343, final size: 258
06AQ20120615:: initial size: 1910, final size: 287
06AQ20120716:: initial size: 548, final size: 75
06AQ20120803:: initial size: 1010, final size: 418
06AQ20131110:: initial size: 304, final size: 184
06AQ20131221:: initial size: 1555, final size: 451
06AQ20140309:: initial size: 391, final size: 260
06AQ20140608:: initial size: 837, final size: 226
06AQ20140707:: initial size: 449, final size: 151
equirectangular4(88.0281, 162.178, 70.7475, 19.6967, limit=45, wrap=True): delta (142.482) exceeds limit (45)
06AQ20140805:: initial size: 1121, unchanged
06AQ20141026:: initial size: 214, final size: 150
06AQ20141203:: initial size: 725, final size: 238
equirectangular4(50.3103, 0.1054, -30.8496, 13.3783, limit=45, wrap=True): delta (81.1599) exceeds limit (45)
06AQ20150204:: initial size: 154, unchanged
06AQ20150519:: initial size: 975, final size: 275
06AQ20150629:: initial size: 1152, final size: 247
equirectangular4(89.9606, 51.1297, 89.9994, 113.632, limit=45, wrap=True): delta (62.5021) exceeds limit (45)
06AQ20150818:: initial size: 718, unchanged
06AQ20151030:: initial size: 158, final size: 141
06AQ20151207:: initial size: 1191, final size: 440
06AQ20160220:: initial size: 567, final size: 294
06AQ20160412:: initial size: 169, final size: 147
06AQ20160614:: initial size: 1145, final size: 257
06AQ20160720:: initial size: 1555, final size: 304
06AQ20170205:: initial size: 792, final size: 232
06AQ20170321:: initial size: 97, unchanged
06AQ20170524:: initial size: 862, final size: 235
06AQ20170723:: initial size: 1735, final size: 153
06AQ20170822:: initial size: 490, final size: 132
06AQ20170912:: initial size: 505, final size: 180
06AQ20200101:: initial size: 49, unchanged
06AQ20200201:: initial size: 62, unchanged
06AQ20200301:: initial size: 73, unchanged
06AQ20200401:: initial size: 96, unchanged
06AQ20200501:: initial size: 123, final size: 14
06AQ20200601:: initial size: 80, unchanged
06AQ20200701:: initial size: 416, final size: 36
equirectangular4(89.953, -32.699, 90.0, 31.672, limit=45, wrap=True): delta (64.371) exceeds limit (45)
06AQ20200801:: initial size: 660, unchanged
06AQ20200901:: initial size: 187, final size: 76
06AQ20201001:: initial size: 56, unchanged
06BE19961010:: initial size: 55, unchanged
06BE19970515:: initial size: 277, final size: 181
06BE19970612:: initial size: 1199, final size: 253
06BE20140710:: initial size: 34, unchanged
06BE20140723:: initial size: 39, unchanged
06CK20060523:: initial size: 100, unchanged
06CK20060715:: initial size: 153, final size: 142
06CK20060821:: initial size: 102, final size: 97
06GA19960613:: initial size: 381, final size: 206
06LB19831130:: initial size: 66, unchanged
06LB19840107:: initial size: 31, unchanged
06LB19840629:: initial size: 53, unchanged
06LB19850110:: initial size: 108, final size: 108
06LB19850313:: initial size: 82, unchanged
06LB19850812:: initial size: 114, final size: 114
06LB19860116:: initial size: 43, unchanged
06LB19860323:: initial size: 42, unchanged
06LB19860801:: initial size: 41, unchanged
06LB19861011:: initial size: 62, unchanged
06LB19861214:: initial size: 88, unchanged
06LB19870221:: initial size: 118, final size: 116
06LB19870501:: initial size: 309, final size: 305
06LB19870721:: initial size: 87, unchanged
06LB19870920:: initial size: 146, final size: 146
06LB19871126:: initial size: 269, final size: 268
06LB19871231:: initial size: 131, final size: 131
06LB19880204:: initial size: 90, unchanged
06M220110623:: initial size: 95, unchanged
06M220180302:: initial size: 128, final size: 102
06M220200117:: initial size: 84, unchanged
06M320120320:: initial size: 56, unchanged
06M320120407:: initial size: 146, final size: 90
06MQ20210627:: initial size: 219, final size: 102
06MT19910903:: initial size: 104, final size: 87
06MT19920510:: initial size: 101, final size: 82
06MT19921229:: initial size: 110, final size: 94
06MT19941012:: initial size: 168, final size: 112
06MT19941119:: initial size: 118, final size: 79
06MT19950714:: initial size: 448, final size: 167
06MT19960607:: initial size: 167, final size: 117
06MT19960622:: initial size: 385, final size: 127
06MT19970106:: initial size: 30, unchanged
06MT19970516:: initial size: 411, final size: 266
06MT19970707:: initial size: 1089, final size: 365
06MT19981228:: initial size: 44, unchanged
06MT20021015:: initial size: 153, final size: 131
06MT20060714:: initial size: 288, final size: 132
06P119910616:: initial size: 31, unchanged
06P119950901:: initial size: 133, final size: 98
06PO20050322:: initial size: 557, final size: 114
06PO20070210:: initial size: 110, final size: 62
06PO20100531:: initial size: 371, final size: 107
06ZG20091213:: initial size: 81, unchanged
06ZG20100115:: initial size: 121, final size: 108
06ZG20100207:: initial size: 84, unchanged
06ZG20100226:: initial size: 90, unchanged
06ZG20100321:: initial size: 80, unchanged
06ZG20100409:: initial size: 70, unchanged
06ZG20100506:: initial size: 94, unchanged
06ZG20100716:: initial size: 66, unchanged
06ZG20100813:: initial size: 113, final size: 109
06ZG20100902:: initial size: 78, unchanged
06ZG20100930:: initial size: 92, unchanged
06ZG20101023:: initial size: 78, unchanged
06ZG20101118:: initial size: 51, unchanged
06ZG20101211:: initial size: 33, unchanged
07AL19951011:: initial size: 245, final size: 54
07AL19960218:: initial size: 141, final size: 61
07AL19970503:: initial size: 660, final size: 199
07AL19990718:: initial size: 75, unchanged
07AL19991101:: initial size: 450, final size: 193
07AL19991129:: initial size: 312, final size: 143
07AL20000113:: initial size: 230, final size: 125
07AL20000210:: initial size: 147, final size: 88
07AL20000305:: initial size: 255, final size: 154
07AL20010513:: initial size: 257, final size: 92
07AL20010607:: initial size: 88, unchanged
07AL20010709:: initial size: 180, final size: 100
07AL20010802:: initial size: 73, unchanged
08AI20000324:: initial size: 162, final size: 136
08AI20010124:: initial size: 217, final size: 181
08AI20010808:: initial size: 82, unchanged
08AI20020131:: initial size: 259, final size: 227
08AI20030206:: initial size: 120, final size: 109
08AI20040227:: initial size: 272, final size: 217
08AI20041225:: initial size: 158, final size: 125
08D820170918:: initial size: 173, final size: 102
08D820180810:: initial size: 10, unchanged
08D820180818:: initial size: 330, final size: 85
08D820190124:: initial size: 45, unchanged
08D820191014:: initial size: 71, unchanged
08D820191117:: initial size: 191, final size: 103
08D820191205:: initial size: 158, final size: 73
08D820221204:: initial size: 280, final size: 113
08D820230227:: initial size: 581, final size: 334
08D820230415:: initial size: 160, final size: 73
08D820230521:: initial size: 209, final size: 124
08D820240120:: initial size: 529, final size: 271
08D820240318:: initial size: 123, final size: 62
08D820240701:: initial size: 353, final size: 185
08D820240815:: initial size: 575, final size: 269
08D820241020:: initial size: 668, final size: 252
08PD20051019:: initial size: 178, final size: 130
08PD20060310:: initial size: 362, final size: 298
08PD20060907:: initial size: 268, final size: 202
096U20150321:: initial size: 17, unchanged
096U20160108:: initial size: 628, final size: 350
096U20160314:: initial size: 216, final size: 156
096U20160426:: initial size: 162, final size: 141
096U20160630:: initial size: 64, unchanged
096U20160817:: initial size: 38, unchanged
096U20160825:: initial size: 78, unchanged
096U20160831:: initial size: 299, final size: 168
096U20160927:: initial size: 79, unchanged
096U20161028:: initial size: 31, unchanged
096U20170114:: initial size: 491, final size: 323
096U20170319:: initial size: 53, unchanged
096U20170411:: initial size: 115, final size: 89
096U20170504:: initial size: 161, final size: 65
096U20170515:: initial size: 143, final size: 95
096U20170831:: initial size: 99, unchanged
096U20170924:: initial size: 183, final size: 120
096U20171011:: initial size: 191, final size: 106
096U20171125:: initial size: 136, final size: 102
096U20180111:: initial size: 308, final size: 220
096U20180302:: initial size: 106, final size: 61
096U20180405:: initial size: 53, unchanged
096U20180418:: initial size: 72, unchanged
096U20180514:: initial size: 82, unchanged
096U20180528:: initial size: 129, final size: 63
096U20180820:: initial size: 29, unchanged
096U20180911:: initial size: 204, final size: 133
096U20181017:: initial size: 170, final size: 124
096U20181122:: initial size: 207, final size: 79
096U20181227:: initial size: 124, final size: 101
096U20190118:: initial size: 588, final size: 312
096U20190314:: initial size: 79, unchanged
096U20190514:: initial size: 96, unchanged
096U20190730:: initial size: 7, unchanged
096U20190807:: initial size: 56, unchanged
096U20190909:: initial size: 72, unchanged
096U20191003:: initial size: 127, final size: 62
096U20191019:: initial size: 543, final size: 198
096U20191223:: initial size: 172, final size: 124
096U20200110:: initial size: 329, final size: 265
096U20200730:: initial size: 124, final size: 20
096U20200827:: initial size: 53, unchanged
096U20201008:: initial size: 272, final size: 188
096U20201113:: initial size: 158, final size: 73
096U20201204:: initial size: 135, final size: 86
096U20210129:: initial size: 622, final size: 434
096U20210414:: initial size: 93, unchanged
096U20210508:: initial size: 169, final size: 127
096U20210611:: initial size: 87, unchanged
096U20210630:: initial size: 141, final size: 128
096U20211110:: initial size: 144, final size: 29
096U20211119:: initial size: 128, final size: 78
096U20211130:: initial size: 96, unchanged
096U20211214:: initial size: 41, unchanged
096U20220319:: initial size: 225, final size: 158
096U20220504:: initial size: 110, final size: 78
096U20220528:: initial size: 329, final size: 201
096U20220714:: initial size: 44, unchanged
096U20220815:: initial size: 42, unchanged
096U20220910:: initial size: 67, unchanged
096U20220930:: initial size: 113, final size: 88
096U20230125:: initial size: 314, final size: 240
096U20230323:: initial size: 374, final size: 208
096U20230511:: initial size: 79, unchanged
096U20230605:: initial size: 33, unchanged
096U20230629:: initial size: 249, final size: 125
096U20230913:: initial size: 225, final size: 95
096U20231009:: initial size: 191, final size: 123
096U20231103:: initial size: 64, unchanged
096U20231115:: initial size: 215, final size: 157
096U20240105:: initial size: 541, final size: 299
096U20240309:: initial size: 115, final size: 81
096U20240330:: initial size: 121, final size: 88
09AR19910926:: initial size: 97, unchanged
09AR19921019:: initial size: 149, final size: 130
09AR19930105:: initial size: 804, final size: 526
09AR19930311:: initial size: 152, final size: 126
09AR19930807:: initial size: 308, final size: 263
09AR19931119:: initial size: 352, final size: 249
equirectangular4(-67.776, 72.397, -43.348, 147.464, limit=45, wrap=True): delta (75.067) exceeds limit (45)
09AR19940101:: initial size: 593, unchanged
09AR19940831:: initial size: 18, unchanged
09AR19941213:: initial size: 243, final size: 184
09AR19950717:: initial size: 32, unchanged
09AR19950916:: initial size: 34, unchanged
09AR19960119:: initial size: 562, final size: 403
09AR19960822:: initial size: 56, unchanged
09AR19970910:: initial size: 22, unchanged
09AR19971114:: initial size: 54, unchanged
09AR19980228:: initial size: 70, unchanged
09AR19980404:: initial size: 7, unchanged
09AR19980715:: initial size: 42, unchanged
09AR19990716:: initial size: 68, unchanged
09AR20011031:: initial size: 225, final size: 130
09AR20060102:: initial size: 974, final size: 572
09AR20110104:: initial size: 488, final size: 218
09AR20110222:: initial size: 553, final size: 221
09AR20120105:: initial size: 346, final size: 201
equirectangular4(-31.9417, 115.599, -66.8708, 66.7085, limit=45, wrap=True): delta (48.8903) exceeds limit (45)
09AR20120215:: initial size: 298, unchanged
09AR20120416:: initial size: 104, final size: 73
09AR20120914:: initial size: 136, final size: 101
09AR20121116:: initial size: 675, final size: 257
09AR20121217:: initial size: 822, final size: 183
09AR20130113:: initial size: 180, final size: 126
09AR20130228:: initial size: 162, final size: 73
09AR20131015:: initial size: 302, final size: 159
equirectangular4(-56.4218, 126.244, -67.146, 73.7061, limit=45, wrap=True): delta (52.5375) exceeds limit (45)
09AR20140129:: initial size: 145, unchanged
09AR20140309:: initial size: 227, final size: 173
09AR20141022:: initial size: 135, final size: 109
09AR20141205:: initial size: 902, final size: 342
09AR20150128:: initial size: 625, final size: 368
09AR20151022:: initial size: 39, unchanged
09AR20151028:: initial size: 257, final size: 186
09AR20151201:: initial size: 102, final size: 42
09AR20151209:: initial size: 202, final size: 139
equirectangular4(-43.6036, 147.29, -62.9043, 73.1134, limit=45, wrap=True): delta (74.1769) exceeds limit (45)
09AR20160111:: initial size: 622, unchanged
09AR20161021:: initial size: 14, unchanged
09AR20161026:: initial size: 256, final size: 215
09AR20161208:: initial size: 1118, final size: 350
09AR20170125:: initial size: 505, final size: 324
09AR20170314:: initial size: 115, final size: 60
09AR20171029:: initial size: 247, final size: 158
09AR20171213:: initial size: 358, final size: 193
09AR20180115:: initial size: 1339, final size: 388
09AR20180308:: initial size: 112, final size: 74
equirectangular4(-61.239, 83.7371, -43.1248, 147.474, limit=45, wrap=True): delta (63.737) exceeds limit (45)
09AR20181025:: initial size: 300, unchanged
09AR20181206:: initial size: 837, final size: 144
09AR20190305:: initial size: 230, final size: 79
09AR20191025:: initial size: 278, final size: 199
09AR20191201:: initial size: 242, final size: 174
09AR20191222:: initial size: 636, final size: 117
equirectangular4(-62.4598, 83.3583, -43.6456, 147.228, limit=45, wrap=True): delta (63.8701) exceeds limit (45)
09AR20200121:: initial size: 700, unchanged
09AR20200310:: initial size: 119, final size: 80
09DB20180327:: initial size: 133, final size: 82
09DB20180328:: initial size: 224, final size: 124
09DB20190814:: initial size: 21, unchanged
09F920180926:: initial size: 232, final size: 2
09F920190419:: initial size: 101, final size: 2
09F920191002:: initial size: 68, unchanged
09F920191214:: initial size: 140, final size: 2
09F920200522:: initial size: 190, final size: 2
09F920201118:: initial size: 175, final size: 2
09F920210523:: initial size: 125, final size: 2
09F920211101:: initial size: 195, final size: 2
09F920220524:: initial size: 221, final size: 2
09F920221201:: initial size: 149, final size: 2
09F920230518:: initial size: 171, final size: 2
09F920231105:: initial size: 144, final size: 2
09FA19920618:: initial size: 27, unchanged
09FA19920625:: initial size: 17, unchanged
09FA20000927:: initial size: 85, unchanged
09FS20091009:: initial size: 824, final size: 2
09FS20100421:: initial size: 349, final size: 2
09FS20100908:: initial size: 814, final size: 2
09FS20110311:: initial size: 599, final size: 2
09FS20110420:: initial size: 91, unchanged
09FS20110826:: initial size: 908, final size: 2
09FS20111018:: initial size: 198, final size: 2
09FS20120208:: initial size: 144, final size: 2
09FS20120417:: initial size: 102, final size: 2
09FS20160805:: initial size: 242, final size: 2
09FS20160817:: initial size: 67, unchanged
09FS20160912:: initial size: 840, final size: 2
09FS20161129:: initial size: 189, final size: 2
09FS20170207:: initial size: 130, final size: 2
09FS20170306:: initial size: 537, final size: 2
09FS20170520:: initial size: 106, final size: 2
09FS20170907:: initial size: 682, final size: 2
09FS20170912:: initial size: 294, final size: 2
09FS20171206:: initial size: 200, final size: 2
09FS20180215:: initial size: 633, final size: 2
09FS20180419:: initial size: 136, final size: 2
09FS20180524:: initial size: 276, final size: 2
09FS20181119:: initial size: 171, final size: 2
09FS20190506:: initial size: 87, unchanged
09FS20191118:: initial size: 267, final size: 2
09FS20201114:: initial size: 167, final size: 2
09FS20210601:: initial size: 88, unchanged
09FS20211117:: initial size: 210, final size: 2
09FS20220509:: initial size: 241, final size: 2
09FS20230219:: initial size: 191, final size: 2
09FS20231018:: initial size: 404, final size: 2
09R920180907:: initial size: 843, final size: 2
09R920190314:: initial size: 653, final size: 2
09R920190904:: initial size: 1183, final size: 2
09R920200306:: initial size: 902, final size: 2
09R920201031:: initial size: 798, final size: 2
09R920210327:: initial size: 717, final size: 2
09R920210921:: initial size: 1333, final size: 2
09R920220516:: initial size: 676, final size: 2
09R920221102:: initial size: 1081, final size: 2
09R920230501:: initial size: 602, final size: 2
09R920231011:: initial size: 1028, final size: 2
09SS19951116:: initial size: 104, final size: 92
09SS19990205:: initial size: 84, unchanged
09SS20080111:: initial size: 119, final size: 64
09SS20080204:: initial size: 435, final size: 174
09SS20080228:: initial size: 274, final size: 86
09SS20080321:: initial size: 27, unchanged
09SS20080405:: initial size: 12, unchanged
09SS20080410:: initial size: 46, unchanged
09SS20080416:: initial size: 19, unchanged
09SS20080430:: initial size: 83, unchanged
09SS20080608:: initial size: 24, unchanged
09SS20080724:: initial size: 97, unchanged
09SS20080812:: initial size: 38, unchanged
09SS20081010:: initial size: 81, unchanged
09SS20090128:: initial size: 26, unchanged
09SS20090203:: initial size: 236, final size: 185
09SS20090422:: initial size: 44, unchanged
09SS20090604:: initial size: 36, unchanged
09SS20090703:: initial size: 67, unchanged
09SS20090729:: initial size: 58, unchanged

In [25]:
all = pd.concat(shorts)
all = all.sort_values(['expocode', 'time'])
figure = px.line_geo(all, lat='latitude', lon='longitude', color='expocode', 
                        hover_data=['expocode', 'time', 'latitude', 'longitude'],
                    )
figure.show()

In [15]:
tdf = pd.read_sql("SELECT distinct expocode FROM tracks WHERE platform_type != 'Mooring' LIMIT 200", con=engine)
tdf

         expocode
0    11SS20141128
1    PAT520150110
2    11SS20150604
3    PANC20200114
4    MLCE20181222
..            ...
195  11SS20180801
196  33KM19980906
197  49UF20080422
198  33WA20131017
199  33LG20121010

[200 rows x 1 columns]

In [16]:
in_set = "','".join(list(tdf['expocode']))
in_set = "'" + in_set + "'"
in_set

"'11SS20141128','PAT520150110','11SS20150604','PANC20200114','MLCE20181222','34FM20230612','64PE20011106','33GC20070717','49P120120502','64SA20051221','26NA20131113','PA1G20161214','319920180328','33GG20090407','33RO20050712','33H420230822','33GC20130521','49RY19900615','ZZ9920070416','33LG20111102','11BU20231120','45CE20190428','353L20100228','11SS20140903','74P220070620','58GS20070304','34FM20150101','26NA20080813','09F920211101','35MJ20230526','49WB20151203','33KF20040607','33KF20020525','PAT520240907','74X120101214','33RO20090416','PAT520201001','33KF20101107','PAT520121026','06AQ20110617','33H420201202','320620130103','BHAF20171022','49UP20071020','26NA20060728','26RA20220420','AG5W20151120','096U20170831','BHNQ20200420','46BS20070206','26NA20191201','33KF20100624','49OX20200317','33HH20170502','33H420220512','34FM20111110','34FM20110302','33H320170110','49WB20180626','18VJ20191003','320620230118','320620010401','PAT520080720','33KF20021123','33LG20151118','33RO20140321','06ZG20100506','PAT520130607','33KF20020310','33GC20051220','33LG20041108','09SS20100508','PANC20140411','PANC20141114','11SS20140401','61TG20130701','49UF20030115','PAT520170508','33RR20230722','09AR20181206','BHNQ20080701','33LG20020729','33BI20210626','61TG20160926','61P220060321','61TG20180205','18PZ19880627','PAT520150521','BHAF20190623','64SA20041016','58SC19970526','33H420220422','33RO20051004','PANC20171208','49P120020827','PAT520111028','33KF20060617','320620160907','11SS20140331','33LG20180413','06LB19861214','320620060228','740H20200119','58G220231116','28AQ20191117','33KF20070928','09AR20180308','33KF20110929','33LG20040613','33H420210624','58PF20070221','492C20000428','AGFO20151226','MLCE20150627','34FM20220701','34FM20080701','BHAF20190519','33GG20180902','33GC20080516','642B20120205','46FR20240504','26RA20210307','332220190921','58GS20170410','49P120090916','096U20171125','49RY19950119','58NC20060717','61TG20231028','58SC19950711','11BE19970702','09AR19940831','PAT520200901','PANC20140427','MLCE20150306','49P120041112','33KF20120319','320620130513','33BI20210414','33LG20141028','49HH19900903','PAT520101026','320620070401','PANC20180227','26NA20111118','11SS20150904','33GC20060323','BHAF20191103','49P120121225','33HH20180812','33LG20030923','74E920141227','54PC19940917','64SA20041113','34FP20040601','PAT520161130','69920200703','58G220230201','33GC20100627','58G220230719','33GC20060524','49UP20150604','353L20101021','91AH20150722','33LG20081231','49P120071218','33KF20110521','33KF20071124','33GG20170809','PANC20190515','33GG20210816','BHNQ20080728','PAT520080628','31FN20100612','49WB20120522','33RO20221006','332220220812','32KZ20051216','BHAF20171008','33GC20041028','49RY19880116','58NC20060809','58SC19990623','33LG20180216','49OX20220521','33KF20051016','33GC20061031','PANC20231113','PAT520130720','26RA20220521','11SS20140909','PAT520181103','BHNQ20090731','BHNQ20090711','06LB19831130','11SS20180801','33KM19980906','49UF20080422','33WA20131017','33LG20121010'"

In [17]:
hdf = pd.read_sql(f"SELECT * FROM tracks WHERE expocode IN ({in_set})", con=engine)
hdf

           expocode                  time   latitude  longitude platform_type
0       69920200703  2020-07-03T13:59:00Z  47.430550  -3.097097          Ship
1       69920200703  2020-07-03T14:27:00Z  47.349260  -3.003854          Ship
2       69920200703  2020-07-03T15:36:00Z  47.307730  -3.048787          Ship
3       69920200703  2020-07-03T16:28:00Z  47.314090  -3.045242          Ship
4       69920200703  2020-07-03T17:37:00Z  47.311530  -3.031797          Ship
...             ...                   ...        ...        ...           ...
42501  ZZ9920070416  2007-05-08T08:51:00Z  50.250000  -4.200012          Ship
42502  ZZ9920070416  2007-05-08T10:47:00Z  50.250000  -4.190002          Ship
42503  ZZ9920070416  2007-05-10T08:38:00Z  50.250000  -4.209991          Ship
42504  ZZ9920070416  2007-05-10T12:24:00Z  50.349998  -4.140015          Ship
42505  ZZ9920070416  2007-05-24T08:58:00Z  50.230000  -4.209991          Ship

[42506 rows x 5 columns]

In [19]:
sdf = pd.read_sql("SELECT distinct expocode FROM tracks WHERE platform_type = 'Mooring' LIMIT 20", con=engine)
sdf

          expocode
0     77FS20130814
1     316420160317
2     316420101127
3     316420160923
4     316420100902
5     316420150622
6   316420070626-2
7     357F20190323
8     316420100117
9     316420040508
10    09FS20180215
11    316420091215
12  316420160308-2
13    189920180101
14    589920110930
15    316420190305
16    589920140614
17    316420210506
18    316420190530
19    35DR20120419

In [20]:
in_buoy = "','".join(list(sdf['expocode']))
in_buoy = "'" + in_buoy + "'"
in_buoy

"'77FS20130814','316420160317','316420101127','316420160923','316420100902','316420150622','316420070626-2','357F20190323','316420100117','316420040508','09FS20180215','316420091215','316420160308-2','189920180101','589920110930','316420190305','589920140614','316420210506','316420190530','35DR20120419'"

In [21]:
bdf = pd.read_sql(f"SELECT * FROM tracks WHERE expocode IN ({in_buoy})", con=engine)
bdf

           expocode                  time   latitude   longitude platform_type
0      189920180101  2018-02-04T00:07:00Z  50.116000 -125.222000       Mooring
1      189920180101  2018-01-01T00:02:00Z  50.116000 -125.222000       Mooring
2      189920180101  2018-01-01T00:13:00Z  50.116000 -125.222000       Mooring
3      189920180101  2018-01-01T01:13:00Z  50.116000 -125.222000       Mooring
4      189920180101  2018-01-01T01:28:00Z  50.116000 -125.222000       Mooring
...             ...                   ...        ...         ...           ...
24358  77FS20130814  2013-09-13T19:30:00Z  57.423333   18.994444       Mooring
24359  77FS20130814  2013-09-14T09:30:00Z  57.423333   18.994444       Mooring
24360  77FS20130814  2013-09-14T15:00:00Z  57.423333   18.994444       Mooring
24361  77FS20130814  2013-09-14T17:00:00Z  57.423333   18.994444       Mooring
24362  77FS20130814  2013-09-15T00:00:00Z  57.423333   18.994444       Mooring

[24363 rows x 5 columns]

In [22]:
import plotly.express as px
import plotly.graph_objects as go
# figure = go.Figure()
# if hdf.shape[0] > 100_000:
#     hdf = hdf.sample(n=100_000)
# expos = list(hdf['expocode'].unique())
# for ex in expos:
#     plot_df = hdf.loc[hdf['expocode']==ex]
#     plot_df = plot_df.sort_values(['time'])
#     trace = go.Scattergeo(lat=plot_df['latitude'], lon=plot_df['longitude'], mode='lines', name=ex)
#     figure.add_trace(trace)
# # figure = px.scatter_geo(hdf, lat='latitude', lon='longitude', color='expocode')
# figure
if hdf.shape[0] > 100_000:
    hdf = hdf.sample(n=100_000)
hdf = hdf.sort_values(['expocode', 'time'])
figure = px.line_geo(hdf, lat='latitude', lon='longitude', color='expocode')
buoy = px.scatter_geo(bdf, lat='latitude', lon='longitude', color='expocode')
figure.add_traces(list(buoy.select_traces()))
figure.show()