In [4]:
import pandas as pd
import os
from sqlalchemy import create_engine
import numpy as np
connection_string = os.environ.get("DATABASE_URL", "postgresql://postgres:docker@127.0.0.1:5432")
engine = create_engine(connection_string)
decimated_url = 'https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated'
full_url = 'https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_fulldata'

In [5]:
df = pd.read_sql('SELECT * from cruises', engine)
df

,expocode,organization,investigators,platform_name,platform_type,qc_flag,socat_version
0,069920180814,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
1,069920180921,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
2,069920181126,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
3,069920190503,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
4,069920190509,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
...,...,...,...,...,...,...,...
8269,WFCH20240426,NOAA AOML,"Wanninkhof, R. : Pierrot, D.",Le Commandant Charcot,Ship,B,2025.0N
8270,WFCH20240506,NOAA AOML,"Wanninkhof, R. : Pierrot, D.",Le Commandant Charcot,Ship,B,2025.0N
8271,WFCH20240516,NOAA AOML,"Wanninkhof, R. : Pierrot, D.",Le Commandant Charcot,Ship,B,2025.0N
8272,WFCH20240528,NOAA AOML,"Wanninkhof, R. : Pierrot, D.",Le Commandant Charcot,Ship,B,2025.0N
8273,ZZ9920070416,Plymouth Marine Lab,"Kitidis, V.",WECO Timeseries,Ship,D,2.0N

In [7]:
to_get =['expocode', 'time', 'latitude', 'longitude', 'platform_type']
dtype_defs = {'expocode': 'str', 'time': 'str', 'latitude': np.float64, 'longitude': np.float64, 'platform_type': 'str'}
vars = ','.join(to_get)
expos = list(df['expocode'])
final_length = 100
for idx, expo in enumerate(expos):
    turl = f'{decimated_url}.csv?{vars}&expocode="{expo}"'
    print(idx, turl)
    track = pd.read_csv(turl, skiprows=[1], dtype=dtype_defs)
    if track.shape[0] > final_length:
        last_row = track.iloc[[-1]]
        m = track.shape[0]
        n = int(track.shape[0]/final_length)
        if n < 1:
            n = 1
        subsamp = track.iloc[::n]
        final = pd.concat([subsamp, last_row], ignore_index=True)
        print(f'initial size: {m}, stride: {n}, final size: {final.shape[0]}')
    track['expocode'] = track['expocode'].astype(str)
    if idx > 0:
        track.to_sql("tracks", con=engine, if_exists="append", index=False)
    else:
        track.to_sql("tracks", con=engine, if_exists="replace", index=False)

0 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920180814"
1 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920180921"
2 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920181126"
3 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920190503"
4 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920190509"
initial size: 167, stride: 1, final size: 168
5 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920190602"
initial size: 109, stride: 1, final size: 110
6 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920190803"
7 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920200703"
initial size: 151, stride: 1, final size: 152
8 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920201009"
9 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920201108"
10 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920201125"
initial size: 161, stride: 1, final size: 162
11 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920201211"
initial size: 126, stride: 1, final size: 127
12 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920201226"
initial size: 103, stride: 1, final size: 104
13 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920210106"
initial size: 164, stride: 1, final size: 165
14 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920211113"
15 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920220226"
16 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920230226"
initial size: 499, stride: 4, final size: 126
17 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920230424"
initial size: 163, stride: 1, final size: 164
18 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920230521"
initial size: 260, stride: 2, final size: 131
19 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="069920240501"
initial size: 194, stride: 1, final size: 195
20 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ19860627"
initial size: 129, stride: 1, final size: 130
21 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ19860928"
initial size: 185, stride: 1, final size: 186
22 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ19911114"
23 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ19911210"
initial size: 210, stride: 2, final size: 106
24 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ19921005"
initial size: 165, stride: 1, final size: 166
25 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ19930128"
initial size: 193, stride: 1, final size: 194
26 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ19930228"
27 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ19931019"
initial size: 247, stride: 2, final size: 125
28 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ19940524"
initial size: 125, stride: 1, final size: 126
29 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ19951112"
initial size: 116, stride: 1, final size: 117
30 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ19960320"
initial size: 149, stride: 1, final size: 150
31 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ19980411"
initial size: 144, stride: 1, final size: 145
32 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ19990327"
initial size: 102, stride: 1, final size: 103
33 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20001004"
initial size: 233, stride: 2, final size: 118
34 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20001026"
initial size: 277, stride: 2, final size: 140
35 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20021126"
initial size: 104, stride: 1, final size: 105
36 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20021214"
initial size: 456, stride: 4, final size: 115
37 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20071203"
initial size: 500, stride: 5, final size: 101
38 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20080209"
initial size: 424, stride: 4, final size: 107
39 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20080416"
initial size: 227, stride: 2, final size: 115
40 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20080624"
initial size: 201, stride: 2, final size: 102
41 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20080705"
initial size: 1947, stride: 19, final size: 104
42 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20090109"
initial size: 391, stride: 3, final size: 132
43 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20090322"
initial size: 134, stride: 1, final size: 135
44 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20090413"
initial size: 380, stride: 3, final size: 128
45 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20090622"
initial size: 684, stride: 6, final size: 115
46 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20090711"
initial size: 668, stride: 6, final size: 113
47 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20090806"
initial size: 1364, stride: 13, final size: 106
48 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20091023"
initial size: 267, stride: 2, final size: 135
49 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20091129"
initial size: 478, stride: 4, final size: 121
50 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20100131"
initial size: 1113, stride: 11, final size: 103
51 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20100408"
initial size: 291, stride: 2, final size: 147
52 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20101026"
initial size: 272, stride: 2, final size: 137
53 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20110617"
initial size: 802, stride: 8, final size: 102
54 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20110715"
initial size: 751, stride: 7, final size: 109
55 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20110806"
initial size: 1057, stride: 10, final size: 107
56 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20111214"
initial size: 366, stride: 3, final size: 123
57 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20120108"
initial size: 551, stride: 5, final size: 112
58 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20120318"
initial size: 413, stride: 4, final size: 105
59 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20120411"
initial size: 343, stride: 3, final size: 116
60 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20120615"
initial size: 1910, stride: 19, final size: 102
61 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20120716"
initial size: 548, stride: 5, final size: 111
62 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20120803"
initial size: 1010, stride: 10, final size: 102
63 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20131110"
initial size: 304, stride: 3, final size: 103
64 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20131221"
initial size: 1555, stride: 15, final size: 105
65 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20140309"
initial size: 391, stride: 3, final size: 132
66 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20140608"
initial size: 837, stride: 8, final size: 106
67 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20140707"
initial size: 449, stride: 4, final size: 114
68 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20140805"
initial size: 1121, stride: 11, final size: 103
69 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20141026"
initial size: 214, stride: 2, final size: 108
70 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20141203"
initial size: 725, stride: 7, final size: 105
71 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20150204"
initial size: 154, stride: 1, final size: 155
72 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20150519"
initial size: 975, stride: 9, final size: 110
73 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20150629"
initial size: 1152, stride: 11, final size: 106
74 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20150818"
initial size: 718, stride: 7, final size: 104
75 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20151030"
initial size: 158, stride: 1, final size: 159
76 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20151207"
initial size: 1191, stride: 11, final size: 110
77 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20160220"
initial size: 567, stride: 5, final size: 115
78 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20160412"
initial size: 169, stride: 1, final size: 170
79 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20160614"
initial size: 1145, stride: 11, final size: 106
80 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20160720"
initial size: 1555, stride: 15, final size: 105
81 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20170205"
initial size: 792, stride: 7, final size: 115
82 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20170321"
83 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20170524"
initial size: 862, stride: 8, final size: 109
84 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20170723"
initial size: 1735, stride: 17, final size: 104
85 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20170822"
initial size: 490, stride: 4, final size: 124
86 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20170912"
initial size: 505, stride: 5, final size: 102
87 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20200101"
88 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20200201"
89 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20200301"
90 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20200401"
91 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20200501"
initial size: 123, stride: 1, final size: 124
92 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20200601"
93 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20200701"
initial size: 416, stride: 4, final size: 105
94 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20200801"
initial size: 660, stride: 6, final size: 111
95 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20200901"
initial size: 187, stride: 1, final size: 188
96 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06AQ20201001"
97 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06BE19961010"
98 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06BE19970515"
initial size: 277, stride: 2, final size: 140
99 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06BE19970612"
initial size: 1199, stride: 11, final size: 110
100 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06BE20140710"
101 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06BE20140723"
102 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06CK20060523"
103 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06CK20060715"
initial size: 153, stride: 1, final size: 154
104 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06CK20060821"
initial size: 102, stride: 1, final size: 103
105 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06GA19960613"
initial size: 381, stride: 3, final size: 128
106 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06LB19831130"
107 https://data.pmel.noaa.gov/socat/erddap/tabledap/socat_v2025_decimated.csv?expocode,time,latitude,longitude,platform_type&expocode="06LB19840107"

In [15]:
tdf = pd.read_sql("SELECT distinct expocode FROM tracks WHERE platform_type != 'Mooring' LIMIT 200", con=engine)
tdf

         expocode
0    11SS20141128
1    PAT520150110
2    11SS20150604
3    PANC20200114
4    MLCE20181222
..            ...
195  11SS20180801
196  33KM19980906
197  49UF20080422
198  33WA20131017
199  33LG20121010

[200 rows x 1 columns]

In [16]:
in_set = "','".join(list(tdf['expocode']))
in_set = "'" + in_set + "'"
in_set

"'11SS20141128','PAT520150110','11SS20150604','PANC20200114','MLCE20181222','34FM20230612','64PE20011106','33GC20070717','49P120120502','64SA20051221','26NA20131113','PA1G20161214','319920180328','33GG20090407','33RO20050712','33H420230822','33GC20130521','49RY19900615','ZZ9920070416','33LG20111102','11BU20231120','45CE20190428','353L20100228','11SS20140903','74P220070620','58GS20070304','34FM20150101','26NA20080813','09F920211101','35MJ20230526','49WB20151203','33KF20040607','33KF20020525','PAT520240907','74X120101214','33RO20090416','PAT520201001','33KF20101107','PAT520121026','06AQ20110617','33H420201202','320620130103','BHAF20171022','49UP20071020','26NA20060728','26RA20220420','AG5W20151120','096U20170831','BHNQ20200420','46BS20070206','26NA20191201','33KF20100624','49OX20200317','33HH20170502','33H420220512','34FM20111110','34FM20110302','33H320170110','49WB20180626','18VJ20191003','320620230118','320620010401','PAT520080720','33KF20021123','33LG20151118','33RO20140321','06ZG20100506','PAT520130607','33KF20020310','33GC20051220','33LG20041108','09SS20100508','PANC20140411','PANC20141114','11SS20140401','61TG20130701','49UF20030115','PAT520170508','33RR20230722','09AR20181206','BHNQ20080701','33LG20020729','33BI20210626','61TG20160926','61P220060321','61TG20180205','18PZ19880627','PAT520150521','BHAF20190623','64SA20041016','58SC19970526','33H420220422','33RO20051004','PANC20171208','49P120020827','PAT520111028','33KF20060617','320620160907','11SS20140331','33LG20180413','06LB19861214','320620060228','740H20200119','58G220231116','28AQ20191117','33KF20070928','09AR20180308','33KF20110929','33LG20040613','33H420210624','58PF20070221','492C20000428','AGFO20151226','MLCE20150627','34FM20220701','34FM20080701','BHAF20190519','33GG20180902','33GC20080516','642B20120205','46FR20240504','26RA20210307','332220190921','58GS20170410','49P120090916','096U20171125','49RY19950119','58NC20060717','61TG20231028','58SC19950711','11BE19970702','09AR19940831','PAT520200901','PANC20140427','MLCE20150306','49P120041112','33KF20120319','320620130513','33BI20210414','33LG20141028','49HH19900903','PAT520101026','320620070401','PANC20180227','26NA20111118','11SS20150904','33GC20060323','BHAF20191103','49P120121225','33HH20180812','33LG20030923','74E920141227','54PC19940917','64SA20041113','34FP20040601','PAT520161130','69920200703','58G220230201','33GC20100627','58G220230719','33GC20060524','49UP20150604','353L20101021','91AH20150722','33LG20081231','49P120071218','33KF20110521','33KF20071124','33GG20170809','PANC20190515','33GG20210816','BHNQ20080728','PAT520080628','31FN20100612','49WB20120522','33RO20221006','332220220812','32KZ20051216','BHAF20171008','33GC20041028','49RY19880116','58NC20060809','58SC19990623','33LG20180216','49OX20220521','33KF20051016','33GC20061031','PANC20231113','PAT520130720','26RA20220521','11SS20140909','PAT520181103','BHNQ20090731','BHNQ20090711','06LB19831130','11SS20180801','33KM19980906','49UF20080422','33WA20131017','33LG20121010'"

In [17]:
hdf = pd.read_sql(f"SELECT * FROM tracks WHERE expocode IN ({in_set})", con=engine)
hdf

           expocode                  time   latitude  longitude platform_type
0       69920200703  2020-07-03T13:59:00Z  47.430550  -3.097097          Ship
1       69920200703  2020-07-03T14:27:00Z  47.349260  -3.003854          Ship
2       69920200703  2020-07-03T15:36:00Z  47.307730  -3.048787          Ship
3       69920200703  2020-07-03T16:28:00Z  47.314090  -3.045242          Ship
4       69920200703  2020-07-03T17:37:00Z  47.311530  -3.031797          Ship
...             ...                   ...        ...        ...           ...
42501  ZZ9920070416  2007-05-08T08:51:00Z  50.250000  -4.200012          Ship
42502  ZZ9920070416  2007-05-08T10:47:00Z  50.250000  -4.190002          Ship
42503  ZZ9920070416  2007-05-10T08:38:00Z  50.250000  -4.209991          Ship
42504  ZZ9920070416  2007-05-10T12:24:00Z  50.349998  -4.140015          Ship
42505  ZZ9920070416  2007-05-24T08:58:00Z  50.230000  -4.209991          Ship

[42506 rows x 5 columns]

In [19]:
sdf = pd.read_sql("SELECT distinct expocode FROM tracks WHERE platform_type = 'Mooring' LIMIT 20", con=engine)
sdf

          expocode
0     77FS20130814
1     316420160317
2     316420101127
3     316420160923
4     316420100902
5     316420150622
6   316420070626-2
7     357F20190323
8     316420100117
9     316420040508
10    09FS20180215
11    316420091215
12  316420160308-2
13    189920180101
14    589920110930
15    316420190305
16    589920140614
17    316420210506
18    316420190530
19    35DR20120419

In [20]:
in_buoy = "','".join(list(sdf['expocode']))
in_buoy = "'" + in_buoy + "'"
in_buoy

"'77FS20130814','316420160317','316420101127','316420160923','316420100902','316420150622','316420070626-2','357F20190323','316420100117','316420040508','09FS20180215','316420091215','316420160308-2','189920180101','589920110930','316420190305','589920140614','316420210506','316420190530','35DR20120419'"

In [21]:
bdf = pd.read_sql(f"SELECT * FROM tracks WHERE expocode IN ({in_buoy})", con=engine)
bdf

           expocode                  time   latitude   longitude platform_type
0      189920180101  2018-02-04T00:07:00Z  50.116000 -125.222000       Mooring
1      189920180101  2018-01-01T00:02:00Z  50.116000 -125.222000       Mooring
2      189920180101  2018-01-01T00:13:00Z  50.116000 -125.222000       Mooring
3      189920180101  2018-01-01T01:13:00Z  50.116000 -125.222000       Mooring
4      189920180101  2018-01-01T01:28:00Z  50.116000 -125.222000       Mooring
...             ...                   ...        ...         ...           ...
24358  77FS20130814  2013-09-13T19:30:00Z  57.423333   18.994444       Mooring
24359  77FS20130814  2013-09-14T09:30:00Z  57.423333   18.994444       Mooring
24360  77FS20130814  2013-09-14T15:00:00Z  57.423333   18.994444       Mooring
24361  77FS20130814  2013-09-14T17:00:00Z  57.423333   18.994444       Mooring
24362  77FS20130814  2013-09-15T00:00:00Z  57.423333   18.994444       Mooring

[24363 rows x 5 columns]

In [22]:
import plotly.express as px
import plotly.graph_objects as go
# figure = go.Figure()
# if hdf.shape[0] > 100_000:
#     hdf = hdf.sample(n=100_000)
# expos = list(hdf['expocode'].unique())
# for ex in expos:
#     plot_df = hdf.loc[hdf['expocode']==ex]
#     plot_df = plot_df.sort_values(['time'])
#     trace = go.Scattergeo(lat=plot_df['latitude'], lon=plot_df['longitude'], mode='lines', name=ex)
#     figure.add_trace(trace)
# # figure = px.scatter_geo(hdf, lat='latitude', lon='longitude', color='expocode')
# figure
if hdf.shape[0] > 100_000:
    hdf = hdf.sample(n=100_000)
hdf = hdf.sort_values(['expocode', 'time'])
figure = px.line_geo(hdf, lat='latitude', lon='longitude', color='expocode')
buoy = px.scatter_geo(bdf, lat='latitude', lon='longitude', color='expocode')
figure.add_traces(list(buoy.select_traces()))
figure.show()