In [15]:
import pandas as pd
import os
from sqlalchemy import create_engine
from constants import decimated_url
table_columns = ['expocode', 'organization', 'investigators', 'platform_name', 'platform_type', 'qc_flag', 'socat_version']
dtype_definitions = {'expocode': 'str', 'organization': 'str', 'investigators': 'str', 'platform_name': 'str', 'platform_type': 'str', 'qc_flag': 'str', 'socat_version': 'str'}

In [17]:
to_get = ','.join(table_columns)
turl = f'{decimated_url}.csv?{to_get}&distinct()'
pdf = pd.read_csv(turl, skiprows=[1], dtype=dtype_definitions)
pdf

,expocode,organization,investigators,platform_name,platform_type,qc_flag,socat_version
0,069920180814,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
1,069920180921,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
2,069920181126,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
3,069920190503,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
4,069920190509,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N
...,...,...,...,...,...,...,...
8269,WFCH20240426,NOAA AOML,"Wanninkhof, R. : Pierrot, D.",Le Commandant Charcot,Ship,B,2025.0N
8270,WFCH20240506,NOAA AOML,"Wanninkhof, R. : Pierrot, D.",Le Commandant Charcot,Ship,B,2025.0N
8271,WFCH20240516,NOAA AOML,"Wanninkhof, R. : Pierrot, D.",Le Commandant Charcot,Ship,B,2025.0N
8272,WFCH20240528,NOAA AOML,"Wanninkhof, R. : Pierrot, D.",Le Commandant Charcot,Ship,B,2025.0N
8273,ZZ9920070416,Plymouth Marine Lab,"Kitidis, V.",WECO Timeseries,Ship,D,2.0N

In [19]:
pdf['expocode'] = pdf['expocode'].astype(str)
p = pdf.loc[pdf['expocode']=='069920180814']
p

,expocode,organization,investigators,platform_name,platform_type,qc_flag,socat_version
0,069920180814,Max Planck Inst,"Landschuetzer, P.",Malizia,Ship,C,2020.0N

In [20]:
connection_string = os.environ.get("DATABASE_URL", "postgresql://postgres:docker@127.0.0.1:5432")
engine = create_engine(connection_string)
pdf.to_sql("cruises", con=engine, if_exists="replace", index=False)

274

In [23]:
edf = pd.read_sql('SELECT * from cruises', con=engine)
expos = sorted(list(edf['expocode']))
if '069920180814' in expos:
    print('Found 069920180814')
else:
    print('expo does not exist')

Found 069920180814